# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Analyzing Musical Instruments
author: Dr. Megan L. Lavengood
email: mlavengo@gmu.edu
description: >- # this means to ignore newlines until "baseurl:"
 Course website for MUSI 810. Fall 2025.
courseno: MUSI 810
semester: Fall 2025
domain: instruments.meganlavengood.com
url: "https://instruments.meganlavengood.com"
# baseurl: "/docs/" # the subpath of your site, e.g. /blog
github_username:  meganlavengood

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Jekyll-TOC
toc:
  min_level: 2
  max_level: 3
  ordered_list: true
  no_toc_section_class: toc-container
  list_id: toc
  list_class: section-nav
  sublist_class: 'toc-sublist'
  item_class: toc-entry
  item_prefix: toc-

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# permalink: /:year/:title:output_ext

future: true

## Class/semester variables

week1: "## Week 1 (Aug 25)"
week2: "## Week 2 (Sep 1)"
week3: "## Week 3 (Sep 8)"
week4: "## Week 4 (Sep 15)"
week5: "## Week 5 (Sep 22)"
week6: "## Week 6 (Sep 29)"
week7: "## Week 7 (Oct 6)"
week8: "## Week 8 (Oct 13)"
week9: "## Week 9 (Oct 20)"
week10: "## Week 10 (Oct 27)"
week11: "## Week 11 (Nov 3)"
week12: "## Week 12 (Nov 10)"
week13: "## Week 13 (Nov 17)"
week14: "## Week 14 (Nov 24)"
week15: "## Week 15 (Dec 1)"

reading2: "### Reading due Wed, Sep 3\n\nKatz 2022, Wright 2024 Ch. 4"
reading3: "### Reading due Wed, Sep 10\n\nTresch and Dolan 2013, De Souza 2017"
reading4: "### Reading due Wed, Sep 17\n\nGotham and Gunn 2016, Cole 2024"
reading5: "### Reading due Wed, Sep 24\n\nEidsheim 2017, Malawey 2020"
reading6: "### Reading due Wed, Oct 1\n\nDuguay 2022, Barna and McLaughlin 2024"
reading7: "### Reading due Wed, Oct 8\n\n0"
reading8: "### Reading due Wed, Oct 15\n\nEasley 2015, Burns 2019"
reading9: "### Reading due Wed, Oct 22\n\nKoozin 2024, chs. 1 & 2"
reading10: "### Reading due Wed, Oct 29\n\nThéberge 1997, Pinch and Trocco 2004"
reading11: "### Reading due Wed, Nov 5\n\nLavengood 2019, Burke 2024"
reading12: "### Reading due Wed, Nov 12\n\nEidsheim 2019, Galuszka 2025"
reading13: "### Reading due Wed, Nov 19\n\n0"
reading14: "### Reading due Wed, Nov 26\n\n"
reading15: "### Reading due Wed, Dec 3\n\n"

homework1: "### Assignment due Sun, Aug 31"
homework2: "### Assignment due Sun, Sep 7"
homework3: "### Assignment due Sun, Sep 14"
homework4: "### Assignment due Sun, Sep 21"
homework5: "### Assignment due Sun, Sep 28"
homework6: "### Assignment due Sun, Oct 5"
homework7: "### Assignment due Sun, Oct 12"
homework8: "### Assignment due Sun, Oct 19"
homework9: "### Assignment due Sun, Oct 26"
homework10: "### Assignment due Sun, Nov 2"
homework11: "### Assignment due Sun, Nov 9"
homework12: "### Assignment due Sun, Nov 16"
homework13: "### Assignment due Sun, Nov 23"
homework14: "### Assignment due Sun, Nov 30"
homework15: "### Assignment due Sun, Dec 7"

final-worksheet: "Wed, Nov 26"
final-video: "Sun, Nov 30"
final-peer: "Wed, Dec 3"
final-early: "Mon, Dec 8"
final-late: "Mon, Dec 15"
final-range: "Dec 8–Dec 15"

discussion3: ""
discussion4: ""
discussion5: ""
discussion6: ""
discussion9: ""
discussion10: ""
discussion13: ""